name: test

on:
  push:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v0.3.0

      - name: Run Forge fmt check
        run: |
          forge --version
          forge fmt --check
        id: fmt_check

      - name: Run Forge build
        run: |
          forge --version
          forge build --skip script --skip test --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
